const links = [
    
    
    'https://vk.com/stop_alko_krasnoarmeysk',
    'https://vk.com/pohmelnaya_korolev',
    'https://vk.com/club222790652',
    'https://vk.com/club222803005',
    'https://vk.com/club222803200',
    'https://vk.com/club222803305',
    'https://vk.com/club222803393',
    'https://vk.com/club222803511',
    'https://vk.com/club222803669',
    'https://vk.com/pohmelnaya_mozhaysk',
    'https://vk.com/club222784884',
    'https://vk.com/club222785024',
    'https://vk.com/club222785072',
    'https://vk.com/stop_alko_roshal',
    'https://vk.com/club222785169',
    'https://vk.com/club222785196',
    'https://vk.com/club222785250',
    'https://vk.com/pohmelnaya_ramenskoe',
    'https://vk.com/pohmelnaya_kolomna',
    'https://vk.com/pohmelnaya_domodedovo',
    'https://vk.com/pohmelnaya_elektrostal',
    'https://vk.com/pohmelnaya_dolgoprudnyy',
    'https://vk.com/pohmelnaya_losinopetrovskiy',
    'https://vk.com/pohmelnaya_pavlovskiyposad',
    'https://vk.com/pohmelnaya_sluzhba_hotkovo',
    'https://vk.com/pohmelnaya_sluzhba_chexov',
    'https://vk.com/pohmelnaya_sluzhba_yahroma',
    'https://vk.com/pohmelnaya_sluzhba_krasnogorsk',
    'https://vk.com/pohmelnaya_sluzhba_pushkino',
    'https://vk.com/pohmelnaya_sluzhba_ivanteevka',
    'https://vk.com/pohmelnaya_sluzhba_egorevsk',
    'https://vk.com/pohmelnaya_sluzhba_vladimir',
    'https://vk.com/pohmelnaya_sluzhba_voronezh',
    'https://vk.com/pohmelnaya_sluzhba_kaluga',
    'https://vk.com/pohmelnaya_sluzhba_kostroma',
    'https://vk.com/pohmelnaya_sluzhba_kursk',
    'https://vk.com/pohmelnaya_sluzhba_lipetsk',
    'https://vk.com/pohmelnaya_sluzhba_ryazan',
    'https://vk.com/pohmelnaya_sluzhba_smolensk',
    'https://vk.com/pohmelnaya_sluzhba_tambov',
    'https://vk.com/pohmelnaya_sluzhba_yaroslavl',
    'https://vk.com/pohmelnaya_sluzhba_spb',
    'https://vk.com/pohmelnaya_vologda',
    'https://vk.com/pohmelnaya_sluzhba_petrozavodsk',
    'https://vk.com/pohmelnaya_sluzhba_astrahan',
    'https://vk.com/pohmelnaya_sluzhba_volgograd',
    'https://vk.com/pohmelnaya_sluzhba_rostovnadonu',
    'https://vk.com/pohmelnaya_sluzhba_pyatigorsk',
    'https://vk.com/pohmelnaya_sluzhba_maykop',
    'https://vk.com/pohmelnaya_sluzhba_mahachkala',
    'https://vk.com/pohmelnaya_sluzhba_nalchik',
    'https://vk.com/stop_alko_kazan',
    'https://vk.com/pohmelnaya_sluzhba_ufa',
    'https://vk.com/pohmelnaya_sluzhba_izhevsk',
    'https://vk.com/stop_alko_nnovgorod',
    'https://vk.com/pohmelnaya_sluzhba_orenburg',
    'https://vk.com/pohmelnaya_sluzhba_penza',
    'https://vk.com/pohmelnaya_sluzhba_perm',
    'https://vk.com/pohmelnaya_sluzhba_samara',
    'https://vk.com/pohmelnaya_sluzhba_toliatti',
    'https://vk.com/pohmelnaya_sluzhba_saratov',
    'https://vk.com/pohmelnaya_sluzhba_ulyanovsk',
    'https://vk.com/pohmelnaya_kurgan',
    'https://vk.com/stop_alko_ekaterinburg',
    'https://vk.com/pohmelnaya_sluzhba_n_tagil',
    'https://vk.com/pohmelnaya_sluzhba_tyumen',
    'https://vk.com/pohmelnaya_sluzhba_chel ',
    'https://vk.com/pohmelnaya_magnitogorsk',
    'https://vk.com/pohmelnaya_surgut',
    'https://vk.com/pohmelnaya_novyyurengoy',
    'https://vk.com/pohmelnaya_sluzhba_barnaul',
    'https://vk.com/pohmelnaya_sluzhba_rubtsovsk',
    'https://vk.com/pohmelnaya_sluzhba_biysk',
    'https://vk.com/pohmelnaya_sluzhba_zarinsk',
    'https://vk.com/pohmelnaya_sluzhba_krasnoyarsk',
    'https://vk.com/pohmelnaya_sluzhba_achinsk',
    'https://vk.com/pohmelnaya_sluzhba_kansk',
    'https://vk.com/pohmelnaya_sluzhba_sharypovo',
    'https://vk.com/pohmelnaya_sluzhba_minusinsk',
    'https://vk.com/pohmelnaya_sluzhba_lesosibirsk',
    'https://vk.com/pohmelnaya_sluzhba_zelenogorsk',
    'https://vk.com/pohmelnaya_sluzhba_nazarovo',
    'https://vk.com/pohmelnaya_sluzhba_borodino',
    'https://vk.com/pohmelnaya_sluzhba_irkutsk',
    'https://vk.com/pohmelnaya_sluzhba_bratsk',
    'https://vk.com/pohmelnaya_sluzhba_angarsk',
    'https://vk.com/pohmelnaya_sluzhba_ust_ilimsk',
    'https://vk.com/pohmelnaya_sluzhba_tulun',
    'https://vk.com/pohmelnaya_sluzhba_ustordynskiy',
    'https://vk.com/pohmelnaya_sluzhba_kemerovo',
    'https://vk.com/pohmelnaya_sluzhba_novokuznetsk',
    'https://vk.com/pohmelnaya_sluzhba_anzherosudzh',
    'https://vk.com/pohmelnaya_sluzhba_tashtagol',
    'https://vk.com/pohmelnaya_sluzhba_yurga',
    'https://vk.com/pohmelnaya_sluzhba_novosibirsk',
    'https://vk.com/pohmelnaya_sluzhba_ob',
    'https://vk.com/pohmelnaya_sluzhba_iskitim',
    'https://vk.com/pohmelnaya_sluzhba_kujbyshev',
    'https://vk.com/pohmelnaya_sluzhba_berdsk',
    'https://vk.com/pohmelnaya_sluzhba_borzya',
    'https://vk.com/pohmelnaya_sluzhba_chita',
    'https://vk.com/pohmelnaya_sluzhba_krasnokamensk',
    'https://vk.com/pohmelnaya_sluzhba_petrovskzaba',
    'https://vk.com/pohmelnaya_sluzhba_sorsk',
    'https://vk.com/pohmelnaya_sluzhba_abakan',
    'https://vk.com/pohmelnaya_sluzhba_chernogorsk',
    'https://vk.com/pohmelnaya_sluzhba_sayanagorsk',
    'https://vk.com/pohmelnaya_sluzhba_omsc',
    'https://vk.com/pohmelnaya_sluzhba_seversk',
    'https://vk.com/pohmelnaya_sluzhba_vladivostok',
    'https://vk.com/pohmelnaya_sluzhba_arsenyev',
    'https://vk.com/pohmelnaya_sluzhba_bolshoi_kamen',
    'https://vk.com/pohmelnaya_sluzhba_dalnegorsk',
    'https://vk.com/pohmelnaya_sluzhba_lesozavodsk',
    'https://vk.com/pohmelnaya_sluzhba_nahodka',
    'https://vk.com/pohmelnaya_sluzhba_spassk_dalniy',
    'https://vk.com/pohmelnaya_sluzhba_ussuriysk',
    'https://vk.com/pohmelnaya_sluzhba_habarovsk',
    'https://vk.com/pohmelnaya_sluzhba_vyazemskiy',
    'https://vk.com/pohmelnaya_komsomolsk_na_amure',
    'https://vk.com/pohmelnaya_sovetskaya_gavan',
    'https://vk.com/pohmelnaya_sluzhba_belogorsk',
    'https://vk.com/pohmelnaya_sluzhba_blagoveshensk',
    'https://vk.com/pohmelnaya_sluzhba_svobodnyj',
    'https://vk.com/pohmelnaya_sluzhba_tynda',
    'https://vk.com/pohmelnaya_sluzhba_anadyr',
    'https://vk.com/pohmelnaya_sluzhba_birobidjan',
    'https://vk.com/pohmelnaya_sluzhba_petropavlovsk',
    'https://vk.com/pohmelnaya_sluzhba_yelizovo',
    'https://vk.com/pohmelnaya_sluzhba_magadan',
]
const nameProduct = [
    'Лечение алкоголизма',
    'Лечение игромании',
    'Нарколог на дом',
    'Психиатр на дом',
    'Вывод из запоя на дому',
]

const description = [
    'Наш центр предлагает профессиональное лечение алкоголизма. Мы предоставляем комплексный подход к лечению алкогольной зависимости, включая медикаментозное лечение, психотерапевтические методики и социальную реабилитацию. Наша команда врачей-наркологов, психологов и социальных работников обеспечивает анонимное и конфиденциальное лечение в нашем стационаре. Мы также предоставляем услуги принудительного лечения от алкоголизма в случаях, когда наркозависимый не может самостоятельно контролировать свое состояние. Контроль качества нашего лечения и поддержка наших пациентов после выписки - это наш приоритет. Свяжитесь с нами, чтобы узнать больше о наших услугах по лечению алкоголизма.',
    'Мы предлагаем профессиональное лечение игромании. Наш центр специализируется на помощи людям, страдающим от зависимости от компьютерных игр и других форм азартных развлечений. Наша команда высококвалифицированных специалистов использует индивидуальный подход к каждому пациенту, чтобы разработать оптимальную стратегию лечения. Мы предлагаем как психотерапевтические методы, так и фармакотерапию, чтобы помочь нашим пациентам преодолеть игровую зависимость. Обращайтесь к нам, если вы ищете квалифицированную помощь в лечении игромании.',
    'Нарколог на дом – это опытный врач, который помогает людям избавиться от зависимости от наркотиков. У нас работают профессиональные наркологи-психиатры, которые помогут Вам преодолеть зависимость и вернуться к здоровому образу жизни. Также мы предоставляем услуги психолога-нарколога, который поможет Вам не только избавиться от зависимости, но и научит правильно реагировать на стресс и негативные эмоции. У нас есть врач-нарколог, который поставит диагноз и назначит лечение в зависимости от степени тяжести заболевания. Если Вам нужен нарколог, обращайтесь к нам! Мы поможем Вам справиться с зависимостью и начать новую жизнь.',
    'Наша клиника предоставляет услуги высококвалифицированных психиатров. Мы также имеем опыт работы в области наркологии и предоставляем комплексную помощь от наших психиатров-наркологов. У нас есть возможность записаться на прием к психиатру, как бесплатно, так и платно. Наши платные консультации проводятся более детально и подробно и включают в себя комплексный подход к лечению. Мы готовы предоставить индивидуальный подход к каждому пациенту и помочь им преодолеть различные психические проблемы. Мы также готовы предоставить справки от психиатра и нарколога для различных нужд, в том числе для получения медицинских справок на работу и других формальностей. Свяжитесь с нами прямо сейчас, чтобы записаться на консультацию к нашим психиатрам или наркологам.',
    'Наша компания предоставляет услуги по выводу из запоя. Мы предлагаем как стационарное лечение, так и лечение на дому. Если вы не можете приехать к нам в нашу клинику, наши специалисты готовы приехать к вам на дом и предоставить необходимую помощь в удобное для вас время. Мы используем инновационные методы лечения, которые помогут вам выйти из состояния алкогольной зависимости. Наши опытные наркологи проводят индивидуальный подход к каждому пациенту, учитывая особенности его организма и состояния. В нашей клинике вы можете получить квалифицированную медицинскую помощь, включая лекарства, инъекции, капельницы и другие современные методы лечения, необходимые для успешного вывода из запоя. Если вам нужна помощь в выводе из запоя, обращайтесь к нам. Мы готовы предоставить качественную помощь и поддержку на всех этапах лечения, как в нашей клинике, так и на дому.',
]
const imageLinks = [
    'img/01.jpg',
    'img/02.jpg',
    'img/03.jpg',
    'img/04.jpg',
    'img/05.jpg',
]

const price = [
    '5000',
    '5000',
    '3000',
    '3000',
    '3000',
]



module.exports = { links, nameProduct, description, imageLinks, price };
